### ISSUE TITLE
FYI: AppsFlyer SKAdNetowrk-Id-list

### ISSUE THREAD

**Issue by fmaschmeier** [skadnetwork/ad-network-ids#17]
you may want to include this list of SKAdNetowrk-Ids:
https://support.appsflyer.com/hc/en-us/articles/360012640377

**Comment by dynamix** [comment]
Good idea! However - looking at their list it seems like they converted everything to lowercase. I'm not sure that is correct. I'll send them a message.

**Comment by fmaschmeier** [comment]
I am unsure about this topic as well, but saw also elsewhere upper and lowercase SKAdNetwork-IDs. And our ID was also lowercase in the E-Mail received from Apple SKAdNetwork Enrollment team.

**Comment by dynamix** [comment]
Yep - I definitely ran into both cases and would assume that the ids are case sensitive. At my company our id was all uppercase.

**Comment by egorlitvinenko** [comment]
> Good idea! However - looking at their list it seems like they converted everything to lowercase. I'm not sure that is correct. I'll send them a message.

Lower case is correct,
https://developer.apple.com/forums/thread/663032

**Comment by dynamix** [comment]
converted everything to lowercase - it is now in their official docs as well: https://developer.apple.com/documentation/storekit/skadnetwork/configuring_the_participating_apps
